name: MplsFilms
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5580022
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: MplsFilms
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#081314'
    - '#293335'
    - '#5c6769'
    - '#ef802c'
    - '#cb9855'
  brandStrength: 0
  lightness: 0.001858486328274012
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
