name: MplsFilms
favicon: null
layout_spectrum: 0.49993
typography_spectrum: 0.5580022
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: MplsFilms
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#387d61'
    - '#59b17e'
    - '#3a5335'
    - '#9ce2a6'
  brandStrength: 0.6875
  lightness: 0.001858486328274012
  saturation: 0.8794650696218014
  rhythmicContrast: 0.2920813644304872
purpose: []
